import"./assets/styles-JE8YjOlG.js";import{i as a,a as r}from"./assets/vendor-4yCzdkXl.js";function v(t,o,e){t.forEach(n=>{n.classList.remove(e)}),o.classList.add(e)}function _(t,o="success"){const e={message:t,position:"topRight",timeout:5e3};switch(o){case"success":a.success(e);break;case"error":a.error(e);break;case"warning":a.warning(e);break;case"info":a.info(e);break;default:a.error({message:"Invalid Type Of toast",position:"topRight",timeout:5e3})}}const c={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalProduct:document.querySelector(".modal-product"),searchFrom:document.querySelector(".search-form")};function w(){c.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",g),c.modalCloseBtn.addEventListener("click",d),c.modal.addEventListener("click",f)}function d(){c.modal.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",g),c.modalCloseBtn.removeEventListener("click",d),c.modal.removeEventListener("click",f)}function g(t){t.code==="Escape"&&d()}function f(t){t.currentTarget===t.target&&d()}const P="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCTS:"/products",PRODUCT_BY_ID:"/products/",SEARCH:"/products/search/"};r.defaults.baseURL=P;async function y(){const{data:t}=await r(i.PRODUCTS);return t}async function E(){const{data:t}=await r(i.CATEGORIES);return t}async function S(t){const{data:o}=await r(`${i.PRODUCTS_BY_CATEGORY}${t}`);return o}async function T(t){const{data:o}=await r(`${i.PRODUCT_BY_ID}${t}`);return o}async function k(t){const{data:o}=await r(`${i.SEARCH}?q=${t}`);return o}function B(t){const e=["All",...t].map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>
`).join("");c.categoriesList.innerHTML=e,document.querySelector(".categories__btn").classList.add("categories__btn--active")}function m(t){const o=t.map(({id:e,thumbnail:n,title:s,category:u,brand:l,price:p})=>`
    <li class="products__item" data-id="${e}">
    <img class="products__image" src="${n}" alt="${s}"/>
    <p class="products__title">${s}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${l}</span></p>
    <p class="products__category">Category: ${u}</p>
    <p class="products__price">Price: ${p}$</p>
 </li>`).join("");c.productsList.insertAdjacentHTML("beforeend",o)}function L(){c.productsList.innerHTML=""}function b(){c.notFound.classList.add("not-found--visible")}function h(){c.notFound.classList.remove("not-found--visible")}function R({images:t,title:o,description:e,shippingInformation:n,price:s,returnPolicy:u,tags:l}){const p=l.map(C=>`<li>${C}</li>`).join(""),$=`<img class="modal-product__img" src="${t[0]}" alt="${o}" />

<div class="modal-product__content"> <p class="modal-product__title">${o}</p>
<ul class="modal-product__tags">${p}</ul> <p class="modal-product__description">${e}</p>
<p class="modal-product__shipping-information">Shipping: ${n}</p>
<p class="modal-product__return-policy">Return Policy: ${u}</p>
<p class="modal-product__price">Price: ${s}$</p>
<button class="modal-product__buy-btn" type="button">Buy</button> </div>`;c.modalProduct.innerHTML=$}async function A(){try{const t=await E();B(t);const{products:o}=await y();m(o)}catch(t){console.log(`Ошибка инициализации странички Home ${t}`)}}async function O(t){const{target:o}=t;if(o.nodeName==="BUTTON"){L();try{const e=o.textContent,n=document.querySelectorAll(".categories__btn");v(n,o,"categories__btn--active");let s;e==="All"?s=await y():s=await S(e),s.products.length>0?(m(s.products),h()):b()}catch(e){console.log(`Ошибка получения продуктов по категории ${e}`)}}}async function D(t){const o=t.target.closest(".products__item");if(!o)return;const e=Number(o.dataset.id),n=await T(e);R(n),w()}async function q(t){t.preventDefault();const o=t.currentTarget.elements.searchValue.value.trim();if(!o){_("Please enter a valid search query","warning");return}L();try{const{products:e}=await k(o);e.length>0?(m(e),h()):b()}catch(e){_(`Ошибка получения продуктов по поиску ${e}`,"error"),console.log(`Ошибка получения продуктов по поиску ${e}`)}}document.addEventListener("DOMContentLoaded",A);c.categoriesList.addEventListener("click",O);c.productsList.addEventListener("click",D);c.searchFrom.addEventListener("submit",q);
//# sourceMappingURL=index.js.map
